// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: authorize_key.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeKey_KeyCmd int32

const (
	AuthorizeKey_LIST   AuthorizeKey_KeyCmd = 0
	AuthorizeKey_SET    AuthorizeKey_KeyCmd = 1
	AuthorizeKey_DELETE AuthorizeKey_KeyCmd = 2
)

// Enum value maps for AuthorizeKey_KeyCmd.
var (
	AuthorizeKey_KeyCmd_name = map[int32]string{
		0: "LIST",
		1: "SET",
		2: "DELETE",
	}
	AuthorizeKey_KeyCmd_value = map[string]int32{
		"LIST":   0,
		"SET":    1,
		"DELETE": 2,
	}
)

func (x AuthorizeKey_KeyCmd) Enum() *AuthorizeKey_KeyCmd {
	p := new(AuthorizeKey_KeyCmd)
	*p = x
	return p
}

func (x AuthorizeKey_KeyCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizeKey_KeyCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_authorize_key_proto_enumTypes[0].Descriptor()
}

func (AuthorizeKey_KeyCmd) Type() protoreflect.EnumType {
	return &file_authorize_key_proto_enumTypes[0]
}

func (x AuthorizeKey_KeyCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizeKey_KeyCmd.Descriptor instead.
func (AuthorizeKey_KeyCmd) EnumDescriptor() ([]byte, []int) {
	return file_authorize_key_proto_rawDescGZIP(), []int{0, 0}
}

// cmd 2
type AuthorizeKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command    AuthorizeKey_KeyCmd `protobuf:"varint,1,opt,name=command,proto3,enum=model.AuthorizeKey_KeyCmd" json:"command,omitempty"`
	PublicKeys []string            `protobuf:"bytes,2,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
}

func (x *AuthorizeKey) Reset() {
	*x = AuthorizeKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorize_key_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeKey) ProtoMessage() {}

func (x *AuthorizeKey) ProtoReflect() protoreflect.Message {
	mi := &file_authorize_key_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeKey.ProtoReflect.Descriptor instead.
func (*AuthorizeKey) Descriptor() ([]byte, []int) {
	return file_authorize_key_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeKey) GetCommand() AuthorizeKey_KeyCmd {
	if x != nil {
		return x.Command
	}
	return AuthorizeKey_LIST
}

func (x *AuthorizeKey) GetPublicKeys() []string {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

var File_authorize_key_proto protoreflect.FileDescriptor

var file_authorize_key_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x8e, 0x01, 0x0a,
	0x0c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x34, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x4b, 0x65, 0x79, 0x2e, 0x4b, 0x65, 0x79, 0x43, 0x6d, 0x64, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x73, 0x22, 0x27, 0x0a, 0x06, 0x4b, 0x65, 0x79, 0x43, 0x6d, 0x64, 0x12, 0x08,
	0x0a, 0x04, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x54, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_authorize_key_proto_rawDescOnce sync.Once
	file_authorize_key_proto_rawDescData = file_authorize_key_proto_rawDesc
)

func file_authorize_key_proto_rawDescGZIP() []byte {
	file_authorize_key_proto_rawDescOnce.Do(func() {
		file_authorize_key_proto_rawDescData = protoimpl.X.CompressGZIP(file_authorize_key_proto_rawDescData)
	})
	return file_authorize_key_proto_rawDescData
}

var file_authorize_key_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authorize_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authorize_key_proto_goTypes = []interface{}{
	(AuthorizeKey_KeyCmd)(0), // 0: model.AuthorizeKey.KeyCmd
	(*AuthorizeKey)(nil),     // 1: model.AuthorizeKey
}
var file_authorize_key_proto_depIdxs = []int32{
	0, // 0: model.AuthorizeKey.command:type_name -> model.AuthorizeKey.KeyCmd
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_authorize_key_proto_init() }
func file_authorize_key_proto_init() {
	if File_authorize_key_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authorize_key_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authorize_key_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authorize_key_proto_goTypes,
		DependencyIndexes: file_authorize_key_proto_depIdxs,
		EnumInfos:         file_authorize_key_proto_enumTypes,
		MessageInfos:      file_authorize_key_proto_msgTypes,
	}.Build()
	File_authorize_key_proto = out.File
	file_authorize_key_proto_rawDesc = nil
	file_authorize_key_proto_goTypes = nil
	file_authorize_key_proto_depIdxs = nil
}
