// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authorize_key.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetAuthorizeKeyRequest struct {
	Command              int32    `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAuthorizeKeyRequest) Reset()         { *m = SetAuthorizeKeyRequest{} }
func (m *SetAuthorizeKeyRequest) String() string { return proto.CompactTextString(m) }
func (*SetAuthorizeKeyRequest) ProtoMessage()    {}
func (*SetAuthorizeKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorize_key_d8625d4c25881a9a, []int{0}
}
func (m *SetAuthorizeKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAuthorizeKeyRequest.Unmarshal(m, b)
}
func (m *SetAuthorizeKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAuthorizeKeyRequest.Marshal(b, m, deterministic)
}
func (dst *SetAuthorizeKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAuthorizeKeyRequest.Merge(dst, src)
}
func (m *SetAuthorizeKeyRequest) XXX_Size() int {
	return xxx_messageInfo_SetAuthorizeKeyRequest.Size(m)
}
func (m *SetAuthorizeKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAuthorizeKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAuthorizeKeyRequest proto.InternalMessageInfo

func (m *SetAuthorizeKeyRequest) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *SetAuthorizeKeyRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type ListAllAuthorizeKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAllAuthorizeKeyRequest) Reset()         { *m = ListAllAuthorizeKeyRequest{} }
func (m *ListAllAuthorizeKeyRequest) String() string { return proto.CompactTextString(m) }
func (*ListAllAuthorizeKeyRequest) ProtoMessage()    {}
func (*ListAllAuthorizeKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorize_key_d8625d4c25881a9a, []int{1}
}
func (m *ListAllAuthorizeKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllAuthorizeKeyRequest.Unmarshal(m, b)
}
func (m *ListAllAuthorizeKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllAuthorizeKeyRequest.Marshal(b, m, deterministic)
}
func (dst *ListAllAuthorizeKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllAuthorizeKeyRequest.Merge(dst, src)
}
func (m *ListAllAuthorizeKeyRequest) XXX_Size() int {
	return xxx_messageInfo_ListAllAuthorizeKeyRequest.Size(m)
}
func (m *ListAllAuthorizeKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllAuthorizeKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllAuthorizeKeyRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SetAuthorizeKeyRequest)(nil), "model.SetAuthorizeKeyRequest")
	proto.RegisterType((*ListAllAuthorizeKeyRequest)(nil), "model.ListAllAuthorizeKeyRequest")
}

func init() { proto.RegisterFile("authorize_key.proto", fileDescriptor_authorize_key_d8625d4c25881a9a) }

var fileDescriptor_authorize_key_d8625d4c25881a9a = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0x2d, 0xc9,
	0xc8, 0x2f, 0xca, 0xac, 0x4a, 0x8d, 0xcf, 0x4e, 0xad, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x0a, 0xe4, 0x12, 0x0b, 0x4e, 0x2d, 0x71, 0x84, 0x29,
	0xf0, 0x4e, 0xad, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0x4f, 0xce,
	0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x85, 0x64,
	0xb9, 0xb8, 0x0a, 0x4a, 0x93, 0x72, 0x32, 0x93, 0x41, 0xc6, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70,
	0x06, 0x71, 0x42, 0x44, 0xbc, 0x53, 0x2b, 0x95, 0x64, 0xb8, 0xa4, 0x7c, 0x32, 0x8b, 0x4b, 0x1c,
	0x73, 0x72, 0xb0, 0x18, 0x9b, 0xc4, 0x06, 0xb6, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x43,
	0x28, 0xa6, 0x32, 0x95, 0x00, 0x00, 0x00,
}
