// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: cli.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CliCmd_Cmd int32

const (
	CliCmd_OPEN   CliCmd_Cmd = 0
	CliCmd_CLOSE  CliCmd_Cmd = 1
	CliCmd_RESIZE CliCmd_Cmd = 2
)

// Enum value maps for CliCmd_Cmd.
var (
	CliCmd_Cmd_name = map[int32]string{
		0: "OPEN",
		1: "CLOSE",
		2: "RESIZE",
	}
	CliCmd_Cmd_value = map[string]int32{
		"OPEN":   0,
		"CLOSE":  1,
		"RESIZE": 2,
	}
)

func (x CliCmd_Cmd) Enum() *CliCmd_Cmd {
	p := new(CliCmd_Cmd)
	*p = x
	return p
}

func (x CliCmd_Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CliCmd_Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_cli_proto_enumTypes[0].Descriptor()
}

func (CliCmd_Cmd) Type() protoreflect.EnumType {
	return &file_cli_proto_enumTypes[0]
}

func (x CliCmd_Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CliCmd_Cmd.Descriptor instead.
func (CliCmd_Cmd) EnumDescriptor() ([]byte, []int) {
	return file_cli_proto_rawDescGZIP(), []int{0, 0}
}

// cmd 4
type CliCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd       CliCmd_Cmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=model.CliCmd_Cmd" json:"cmd,omitempty"`
	Session   string     `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	RequestId string     `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Pid       uint32     `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Width     uint32     `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height    uint32     `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *CliCmd) Reset() {
	*x = CliCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cli_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CliCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CliCmd) ProtoMessage() {}

func (x *CliCmd) ProtoReflect() protoreflect.Message {
	mi := &file_cli_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CliCmd.ProtoReflect.Descriptor instead.
func (*CliCmd) Descriptor() ([]byte, []int) {
	return file_cli_proto_rawDescGZIP(), []int{0}
}

func (x *CliCmd) GetCmd() CliCmd_Cmd {
	if x != nil {
		return x.Cmd
	}
	return CliCmd_OPEN
}

func (x *CliCmd) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *CliCmd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CliCmd) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CliCmd) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CliCmd) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_cli_proto protoreflect.FileDescriptor

var file_cli_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x6c, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x22, 0xce, 0x01, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x43, 0x6d, 0x64, 0x12, 0x23, 0x0a,
	0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x43, 0x6c, 0x69, 0x43, 0x6d, 0x64, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x03, 0x63,
	0x6d, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x26, 0x0a, 0x03, 0x43,
	0x6d, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x53, 0x49, 0x5a,
	0x45, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cli_proto_rawDescOnce sync.Once
	file_cli_proto_rawDescData = file_cli_proto_rawDesc
)

func file_cli_proto_rawDescGZIP() []byte {
	file_cli_proto_rawDescOnce.Do(func() {
		file_cli_proto_rawDescData = protoimpl.X.CompressGZIP(file_cli_proto_rawDescData)
	})
	return file_cli_proto_rawDescData
}

var file_cli_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cli_proto_goTypes = []interface{}{
	(CliCmd_Cmd)(0), // 0: model.CliCmd.Cmd
	(*CliCmd)(nil),  // 1: model.CliCmd
}
var file_cli_proto_depIdxs = []int32{
	0, // 0: model.CliCmd.cmd:type_name -> model.CliCmd.Cmd
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cli_proto_init() }
func file_cli_proto_init() {
	if File_cli_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cli_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CliCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cli_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cli_proto_goTypes,
		DependencyIndexes: file_cli_proto_depIdxs,
		EnumInfos:         file_cli_proto_enumTypes,
		MessageInfos:      file_cli_proto_msgTypes,
	}.Build()
	File_cli_proto = out.File
	file_cli_proto_rawDesc = nil
	file_cli_proto_goTypes = nil
	file_cli_proto_depIdxs = nil
}
