// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cli.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CliCmd_Cmd int32

const (
	CliCmd_OPEN  CliCmd_Cmd = 0
	CliCmd_CLOSE CliCmd_Cmd = 1
)

var CliCmd_Cmd_name = map[int32]string{
	0: "OPEN",
	1: "CLOSE",
}
var CliCmd_Cmd_value = map[string]int32{
	"OPEN":  0,
	"CLOSE": 1,
}

func (x CliCmd_Cmd) String() string {
	return proto.EnumName(CliCmd_Cmd_name, int32(x))
}
func (CliCmd_Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cli_4269c20d3c93b829, []int{0, 0}
}

// cmd 0
type CliCmd struct {
	Cmd                  CliCmd_Cmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=model.CliCmd_Cmd" json:"cmd,omitempty"`
	Session              string     `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CliCmd) Reset()         { *m = CliCmd{} }
func (m *CliCmd) String() string { return proto.CompactTextString(m) }
func (*CliCmd) ProtoMessage()    {}
func (*CliCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_4269c20d3c93b829, []int{0}
}
func (m *CliCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliCmd.Unmarshal(m, b)
}
func (m *CliCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliCmd.Marshal(b, m, deterministic)
}
func (dst *CliCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliCmd.Merge(dst, src)
}
func (m *CliCmd) XXX_Size() int {
	return xxx_messageInfo_CliCmd.Size(m)
}
func (m *CliCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CliCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CliCmd proto.InternalMessageInfo

func (m *CliCmd) GetCmd() CliCmd_Cmd {
	if m != nil {
		return m.Cmd
	}
	return CliCmd_OPEN
}

func (m *CliCmd) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func init() {
	proto.RegisterType((*CliCmd)(nil), "model.CliCmd")
	proto.RegisterEnum("model.CliCmd_Cmd", CliCmd_Cmd_name, CliCmd_Cmd_value)
}

func init() { proto.RegisterFile("cli.proto", fileDescriptor_cli_4269c20d3c93b829) }

var fileDescriptor_cli_4269c20d3c93b829 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xce, 0xc9, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x4a, 0xe6, 0x62,
	0x73, 0xce, 0xc9, 0x74, 0xce, 0x4d, 0x11, 0x52, 0xe6, 0x62, 0x4e, 0xce, 0x4d, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd4, 0x03, 0x4b, 0xeb, 0x41, 0xe4, 0xf4, 0x9c, 0x73, 0x53, 0x82,
	0x40, 0xb2, 0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa9, 0xc5, 0xc5, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92, 0x14, 0x17, 0x33, 0xc8, 0x14, 0x0e, 0x2e, 0x16, 0xff,
	0x00, 0x57, 0x3f, 0x01, 0x06, 0x21, 0x4e, 0x2e, 0x56, 0x67, 0x1f, 0xff, 0x60, 0x57, 0x01, 0xc6,
	0x24, 0x36, 0xb0, 0x95, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xa4, 0xee, 0xef, 0x7f,
	0x00, 0x00, 0x00,
}
