// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cli_pipe.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// cmd 3
type CliPipe struct {
	Session              int32    `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CliPipe) Reset()         { *m = CliPipe{} }
func (m *CliPipe) String() string { return proto.CompactTextString(m) }
func (*CliPipe) ProtoMessage()    {}
func (*CliPipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_cli_pipe_8a009f33225fafde, []int{0}
}
func (m *CliPipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliPipe.Unmarshal(m, b)
}
func (m *CliPipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliPipe.Marshal(b, m, deterministic)
}
func (dst *CliPipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliPipe.Merge(dst, src)
}
func (m *CliPipe) XXX_Size() int {
	return xxx_messageInfo_CliPipe.Size(m)
}
func (m *CliPipe) XXX_DiscardUnknown() {
	xxx_messageInfo_CliPipe.DiscardUnknown(m)
}

var xxx_messageInfo_CliPipe proto.InternalMessageInfo

func (m *CliPipe) GetSession() int32 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *CliPipe) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CliPipe)(nil), "model.CliPipe")
}

func init() { proto.RegisterFile("cli_pipe.proto", fileDescriptor_cli_pipe_8a009f33225fafde) }

var fileDescriptor_cli_pipe_8a009f33225fafde = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xc9, 0x8c,
	0x2f, 0xc8, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49,
	0xcd, 0x51, 0x32, 0xe7, 0x62, 0x77, 0xce, 0xc9, 0x0c, 0xc8, 0x2c, 0x48, 0x15, 0x92, 0xe0, 0x62,
	0x2f, 0x4e, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0x93, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71,
	0x85, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xc0,
	0xec, 0x24, 0x36, 0xb0, 0x31, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0x2c, 0x9f, 0xd0,
	0x58, 0x00, 0x00, 0x00,
}
