// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: cli_pipe.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// cmd 3
type CliPipe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Pid     uint32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DataLen uint32 `protobuf:"varint,4,opt,name=data_len,json=dataLen,proto3" json:"data_len,omitempty"`
}

func (x *CliPipe) Reset() {
	*x = CliPipe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cli_pipe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CliPipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CliPipe) ProtoMessage() {}

func (x *CliPipe) ProtoReflect() protoreflect.Message {
	mi := &file_cli_pipe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CliPipe.ProtoReflect.Descriptor instead.
func (*CliPipe) Descriptor() ([]byte, []int) {
	return file_cli_pipe_proto_rawDescGZIP(), []int{0}
}

func (x *CliPipe) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *CliPipe) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CliPipe) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CliPipe) GetDataLen() uint32 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

var File_cli_pipe_proto protoreflect.FileDescriptor

var file_cli_pipe_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x5f, 0x70, 0x69, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x64, 0x0a, 0x07, 0x43, 0x6c, 0x69, 0x50, 0x69,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65, 0x6e, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cli_pipe_proto_rawDescOnce sync.Once
	file_cli_pipe_proto_rawDescData = file_cli_pipe_proto_rawDesc
)

func file_cli_pipe_proto_rawDescGZIP() []byte {
	file_cli_pipe_proto_rawDescOnce.Do(func() {
		file_cli_pipe_proto_rawDescData = protoimpl.X.CompressGZIP(file_cli_pipe_proto_rawDescData)
	})
	return file_cli_pipe_proto_rawDescData
}

var file_cli_pipe_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cli_pipe_proto_goTypes = []interface{}{
	(*CliPipe)(nil), // 0: model.CliPipe
}
var file_cli_pipe_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cli_pipe_proto_init() }
func file_cli_pipe_proto_init() {
	if File_cli_pipe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cli_pipe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CliPipe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cli_pipe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cli_pipe_proto_goTypes,
		DependencyIndexes: file_cli_pipe_proto_depIdxs,
		MessageInfos:      file_cli_pipe_proto_msgTypes,
	}.Build()
	File_cli_pipe_proto = out.File
	file_cli_pipe_proto_rawDesc = nil
	file_cli_pipe_proto_goTypes = nil
	file_cli_pipe_proto_depIdxs = nil
}
