kind: pipeline
name: default

steps:
- name: build
  image: golang:1.18.3
  commands:
  - mkdir -p $(go env GOPATH)/src/duguying
  - ln -s $(pwd) $(go env GOPATH)/src/duguying/studio
  - ./control ptag
  - ./control build
  - ./control prebuild
  - ./control dtag

- name: docker
  image: plugins/docker
  settings:
    repo: git.duguying.net/duguying/studio
    registry: git.duguying.net
    username:
      from_secret: git_docker_username
    password:
      from_secret: git_docker_password
  when:
    event:
      - tag