kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - mkdir -p $(go env GOPATH)/src/duguying
  - ln -s $(pwd) $(go env GOPATH)/src/duguying/studio
  - ./control build

- name: docker
  image: plugins/docker
  settings:
    repo: duguying/studio
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag