kind: pipeline
name: default

steps:
- name: build
  image: golang:1.18.3
  commands:
  - mkdir -p $(go env GOPATH)/src/duguying
  - ln -s $(pwd) $(go env GOPATH)/src/duguying/studio
  - ./control build
  - ./control prebuild
  - ./control dtag

- name: docker
  image: plugins/docker
  settings:
    repo: duguying/studio
    registry: ghcr.io
    mirror: registry.cn-hangzhou.aliyuncs.com
    add_host: 
    - registry-1.docker.io:54.174.228.110
    - auth.docker.io:18.209.128.237
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag