kind: pipeline
name: default

steps:
- name: build
  image: golang:1.18.3
  commands:
  - mkdir -p $(go env GOPATH)/src/duguying
  - ln -s $(pwd) $(go env GOPATH)/src/duguying/studio
  - ./control ptag
  - ./control build
  - ./control prebuild
  - ./control dtag

- name: docker
  image: plugins/docker
  custom_dns: 192.168.1.1
  settings:
    repo: duguying/studio
    registry: ghcr.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag